
version: 0.2
env:
  git-credential-helper: yes
  # parameter-store:
  #   GITHUB_REPO: "GITHUB_REPO"
phases:

  pre_build:
    commands:
      - echo "Cloning git-credentials tools..."
      - git clone https://github.com/awslabs/git-secrets.git
  build:
    commands:
      - echo "Build started on $(date)"
      - sudo ln -s "$(which echo)" /usr/local/bin/say
      - cd git-secrets
      - make install
      - cd $CODEBUILD_SRC_DIR
      - echo "Cloning Source Code..."
      - git clone $REPO_URL
      - export TERM=xterm-256color
      - cd $PATH_TO_SOURCE_CODE
      - git secrets --install
      - git secrets --register-aws
      ## Adding additional patterns, for example password
      - git secrets --scan --recursive
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  type: zip
  files: '**/*'